---
abstract: 'All Map::Metro maps'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires:
  Test::More: '0.96'
  Test::NoTabs: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, Dist::Iller version 0.1002, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-MapMetro-Maps
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Map::Metro: '0.2101'
  Map::Metro::Plugin::Map::Amsterdam: '0'
  Map::Metro::Plugin::Map::Athens: '0'
  Map::Metro::Plugin::Map::Barcelona: '0'
  Map::Metro::Plugin::Map::Berlin: '0'
  Map::Metro::Plugin::Map::Copenhagen: '0'
  Map::Metro::Plugin::Map::Gothenburg: '0'
  Map::Metro::Plugin::Map::Helsinki: '0'
  Map::Metro::Plugin::Map::Oslo: '0'
  Map::Metro::Plugin::Map::Stockholm: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/Csson/p5-Task-MapMetro-Maps/issues
  homepage: https://github.com/Csson/p5-Task-MapMetro-Maps
  repository: https://github.com/Csson/p5-Task-MapMetro-Maps.git
version: '0.1000'
